### ISSUE TITLE
Add support for reading ION file in Elastic bulk operation

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-elasticsearch#18]
### Feature description

We generally treat ION as first class citizen in Kestra, however with the Bulk operation (possibly other operations too) we only support the JSON format for Elasticsearch

e.g. 
https://github.com/kestra-io/plugin-elasticsearch/blob/ced8dc00f12ea9763e7afd74af1c629e43d56de9/src/main/java/io/kestra/plugin/elasticsearch/Bulk.java#L68

Expectation here is that if uri of ION file is provided this should succeed. 

As an example to test

```
id: large_file_process
namespace: demo
tasks:
  - id: get_csv
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
  - id: to_ion
    type: io.kestra.plugin.serdes.csv.CsvToIon
    from: "{{outputs.get_csv.uri}}"
  - id: add_index
    type: io.kestra.plugin.scripts.jython.FileTransform
    from: "{{outputs.to_ion.uri}}"
    script: |
      rows = [{"index" : {"_index": "new-index"}}, row]
  - id: to_json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{outputs.add_index.uri}}"
    disabled: true
  - id: bulk_update
    type: io.kestra.plugin.elasticsearch.Bulk
    connection:
      hosts:
        - "{{secret('aws-os-domain')}}"
      basicAuth:
        username: "{{secret('aws-os-user')}}"
        password: "{{secret('aws-os-password')}}"
    from: "{{ outputs.add_index.uri}}"
```

Without the to_json step this will fail
